#if !canImport(ObjectiveC)
import XCTest

extension SyntaxValidatingVisitorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SyntaxValidatingVisitorTests = [
        ("testInvalidSyntax", testInvalidSyntax),
        ("testValidSyntax", testValidSyntax),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SyntaxValidatingVisitorTests.__allTests__SyntaxValidatingVisitorTests),
    ]
}
#endif
