#if !canImport(ObjectiveC)
import XCTest

extension ConfigurationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConfigurationTests = [
        ("testDefaultConfigurationIsSameAsEmptyDecode", testDefaultConfigurationIsSameAsEmptyDecode),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ConfigurationTests.__allTests__ConfigurationTests),
    ]
}
#endif
