#if !canImport(ObjectiveC)
import XCTest

extension WhitespaceLintTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WhitespaceLintTests = [
        ("testAddLines", testAddLines),
        ("testIndentation", testIndentation),
        ("testLineLength", testLineLength),
        ("testRemoveLines", testRemoveLines),
        ("testSpacing", testSpacing),
        ("testTrailingWhitespace", testTrailingWhitespace),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(WhitespaceLintTests.__allTests__WhitespaceLintTests),
    ]
}
#endif
