//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2019 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

// This file is automatically generated with generate-pipeline. Do Not Edit!

import SwiftFormatCore
import SwiftFormatRules
import SwiftSyntax

extension LintPipeline {

  func visit(_ node: ArrayExprSyntax) -> SyntaxVisitorContinueKind {
    _ = MultiLineTrailingCommas(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: AsExprSyntax) -> SyntaxVisitorContinueKind {
    _ = NeverForceUnwrap(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: AssociatedtypeDeclSyntax) -> SyntaxVisitorContinueKind {
    _ = BeginDocumentationCommentWithOneLineSummary(context: context).visit(node)
    _ = NoLeadingUnderscores(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: ClassDeclSyntax) -> SyntaxVisitorContinueKind {
    _ = AllPublicDeclarationsHaveDocumentation(context: context).visit(node)
    _ = BeginDocumentationCommentWithOneLineSummary(context: context).visit(node)
    _ = DontRepeatTypeInStaticProperties(context: context).visit(node)
    _ = NoLeadingUnderscores(context: context).visit(node)
    _ = UseEnumForNamespacing(context: context).visit(node)
    _ = UseTripleSlashForDocumentationComments(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: ClosureExprSyntax) -> SyntaxVisitorContinueKind {
    _ = OneVariableDeclarationPerLine(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: CodeBlockSyntax) -> SyntaxVisitorContinueKind {
    _ = AmbiguousTrailingClosureOverload(context: context).visit(node)
    _ = DoNotUseSemicolons(context: context).visit(node)
    _ = OneVariableDeclarationPerLine(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: ConditionElementSyntax) -> SyntaxVisitorContinueKind {
    _ = NoParensAroundConditions(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: DeinitializerDeclSyntax) -> SyntaxVisitorContinueKind {
    _ = AllPublicDeclarationsHaveDocumentation(context: context).visit(node)
    _ = BeginDocumentationCommentWithOneLineSummary(context: context).visit(node)
    _ = UseTripleSlashForDocumentationComments(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: DictionaryExprSyntax) -> SyntaxVisitorContinueKind {
    _ = MultiLineTrailingCommas(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: EnumCaseElementSyntax) -> SyntaxVisitorContinueKind {
    _ = AlwaysUseLowerCamelCase(context: context).visit(node)
    _ = NoLeadingUnderscores(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: EnumDeclSyntax) -> SyntaxVisitorContinueKind {
    _ = BeginDocumentationCommentWithOneLineSummary(context: context).visit(node)
    _ = DontRepeatTypeInStaticProperties(context: context).visit(node)
    _ = FullyIndirectEnum(context: context).visit(node)
    _ = NoLeadingUnderscores(context: context).visit(node)
    _ = OneCasePerLine(context: context).visit(node)
    _ = UseTripleSlashForDocumentationComments(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: ExtensionDeclSyntax) -> SyntaxVisitorContinueKind {
    _ = DontRepeatTypeInStaticProperties(context: context).visit(node)
    _ = NoAccessLevelOnExtensionDeclaration(context: context).visit(node)
    _ = UseTripleSlashForDocumentationComments(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: ForcedValueExprSyntax) -> SyntaxVisitorContinueKind {
    _ = NeverForceUnwrap(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: FunctionCallExprSyntax) -> SyntaxVisitorContinueKind {
    _ = NoEmptyTrailingClosureParentheses(context: context).visit(node)
    _ = OnlyOneTrailingClosureArgument(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: FunctionDeclSyntax) -> SyntaxVisitorContinueKind {
    _ = AllPublicDeclarationsHaveDocumentation(context: context).visit(node)
    _ = AlwaysUseLowerCamelCase(context: context).visit(node)
    _ = BeginDocumentationCommentWithOneLineSummary(context: context).visit(node)
    _ = NoLeadingUnderscores(context: context).visit(node)
    _ = UseTripleSlashForDocumentationComments(context: context).visit(node)
    _ = ValidateDocumentationComments(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: FunctionParameterSyntax) -> SyntaxVisitorContinueKind {
    _ = NoLeadingUnderscores(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: FunctionSignatureSyntax) -> SyntaxVisitorContinueKind {
    _ = NoVoidReturnOnFunctionSignature(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: FunctionTypeSyntax) -> SyntaxVisitorContinueKind {
    _ = ReturnVoidInsteadOfEmptyTuple(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: GenericParameterSyntax) -> SyntaxVisitorContinueKind {
    _ = NoLeadingUnderscores(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: IdentifierPatternSyntax) -> SyntaxVisitorContinueKind {
    _ = IdentifiersMustBeASCII(context: context).visit(node)
    _ = NoLeadingUnderscores(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: IfStmtSyntax) -> SyntaxVisitorContinueKind {
    _ = NoParensAroundConditions(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: InitializerDeclSyntax) -> SyntaxVisitorContinueKind {
    _ = AllPublicDeclarationsHaveDocumentation(context: context).visit(node)
    _ = BeginDocumentationCommentWithOneLineSummary(context: context).visit(node)
    _ = UseTripleSlashForDocumentationComments(context: context).visit(node)
    _ = ValidateDocumentationComments(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: IntegerLiteralExprSyntax) -> SyntaxVisitorContinueKind {
    _ = GroupNumericLiterals(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: MemberDeclBlockSyntax) -> SyntaxVisitorContinueKind {
    _ = AmbiguousTrailingClosureOverload(context: context).visit(node)
    _ = BlankLineBetweenMembers(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: PatternBindingSyntax) -> SyntaxVisitorContinueKind {
    _ = UseSingleLinePropertyGetter(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: PrecedenceGroupDeclSyntax) -> SyntaxVisitorContinueKind {
    _ = NoLeadingUnderscores(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: ProtocolDeclSyntax) -> SyntaxVisitorContinueKind {
    _ = AllPublicDeclarationsHaveDocumentation(context: context).visit(node)
    _ = BeginDocumentationCommentWithOneLineSummary(context: context).visit(node)
    _ = DontRepeatTypeInStaticProperties(context: context).visit(node)
    _ = NoLeadingUnderscores(context: context).visit(node)
    _ = UseTripleSlashForDocumentationComments(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: RepeatWhileStmtSyntax) -> SyntaxVisitorContinueKind {
    _ = NoParensAroundConditions(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: SimpleTypeIdentifierSyntax) -> SyntaxVisitorContinueKind {
    _ = UseShorthandTypeNames(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: SourceFileSyntax) -> SyntaxVisitorContinueKind {
    _ = AmbiguousTrailingClosureOverload(context: context).visit(node)
    _ = DoNotUseSemicolons(context: context).visit(node)
    _ = NeverForceUnwrap(context: context).visit(node)
    _ = NeverUseForceTry(context: context).visit(node)
    _ = NeverUseImplicitlyUnwrappedOptionals(context: context).visit(node)
    _ = OneVariableDeclarationPerLine(context: context).visit(node)
    _ = OrderedImports(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: SpecializeExprSyntax) -> SyntaxVisitorContinueKind {
    _ = UseShorthandTypeNames(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: StructDeclSyntax) -> SyntaxVisitorContinueKind {
    _ = AllPublicDeclarationsHaveDocumentation(context: context).visit(node)
    _ = BeginDocumentationCommentWithOneLineSummary(context: context).visit(node)
    _ = DontRepeatTypeInStaticProperties(context: context).visit(node)
    _ = NoLeadingUnderscores(context: context).visit(node)
    _ = UseEnumForNamespacing(context: context).visit(node)
    _ = UseSynthesizedInitializer(context: context).visit(node)
    _ = UseTripleSlashForDocumentationComments(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: SubscriptDeclSyntax) -> SyntaxVisitorContinueKind {
    _ = AllPublicDeclarationsHaveDocumentation(context: context).visit(node)
    _ = BeginDocumentationCommentWithOneLineSummary(context: context).visit(node)
    _ = UseTripleSlashForDocumentationComments(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: SwitchCaseLabelSyntax) -> SyntaxVisitorContinueKind {
    _ = NoLabelsInCasePatterns(context: context).visit(node)
    _ = UseLetInEveryBoundCaseVariable(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: SwitchStmtSyntax) -> SyntaxVisitorContinueKind {
    _ = CaseIndentLevelEqualsSwitch(context: context).visit(node)
    _ = NoCasesWithOnlyFallthrough(context: context).visit(node)
    _ = NoParensAroundConditions(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: TokenSyntax) -> SyntaxVisitorContinueKind {
    _ = NoBlockComments(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: TryExprSyntax) -> SyntaxVisitorContinueKind {
    _ = NeverUseForceTry(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: TypealiasDeclSyntax) -> SyntaxVisitorContinueKind {
    _ = AllPublicDeclarationsHaveDocumentation(context: context).visit(node)
    _ = BeginDocumentationCommentWithOneLineSummary(context: context).visit(node)
    _ = NoLeadingUnderscores(context: context).visit(node)
    _ = UseTripleSlashForDocumentationComments(context: context).visit(node)
    return .visitChildren
  }

  func visit(_ node: VariableDeclSyntax) -> SyntaxVisitorContinueKind {
    _ = AllPublicDeclarationsHaveDocumentation(context: context).visit(node)
    _ = AlwaysUseLowerCamelCase(context: context).visit(node)
    _ = BeginDocumentationCommentWithOneLineSummary(context: context).visit(node)
    _ = NeverUseImplicitlyUnwrappedOptionals(context: context).visit(node)
    _ = UseTripleSlashForDocumentationComments(context: context).visit(node)
    return .visitChildren
  }
}

extension FormatPipeline {

  func visit(_ node: Syntax) -> Syntax {
    var node = node
    node = BlankLineBetweenMembers(context: context).visit(node)
    node = DoNotUseSemicolons(context: context).visit(node)
    node = FullyIndirectEnum(context: context).visit(node)
    node = GroupNumericLiterals(context: context).visit(node)
    node = MultiLineTrailingCommas(context: context).visit(node)
    node = NoAccessLevelOnExtensionDeclaration(context: context).visit(node)
    node = NoBlockComments(context: context).visit(node)
    node = NoCasesWithOnlyFallthrough(context: context).visit(node)
    node = NoEmptyTrailingClosureParentheses(context: context).visit(node)
    node = NoLabelsInCasePatterns(context: context).visit(node)
    node = NoParensAroundConditions(context: context).visit(node)
    node = NoVoidReturnOnFunctionSignature(context: context).visit(node)
    node = OneCasePerLine(context: context).visit(node)
    node = OneVariableDeclarationPerLine(context: context).visit(node)
    node = OrderedImports(context: context).visit(node)
    node = ReturnVoidInsteadOfEmptyTuple(context: context).visit(node)
    node = UseEnumForNamespacing(context: context).visit(node)
    node = UseShorthandTypeNames(context: context).visit(node)
    node = UseSingleLinePropertyGetter(context: context).visit(node)
    node = UseTripleSlashForDocumentationComments(context: context).visit(node)
    return node
  }
}
