#if !canImport(ObjectiveC)
import XCTest

extension RuleMaskTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RuleMaskTests = [
        ("testDirectiveWithRulesList", testDirectiveWithRulesList),
        ("testDuplicateNested", testDuplicateNested),
        ("testIgnoreTwoRules", testIgnoreTwoRules),
        ("testNamelessDirectiveAffectsAllRules", testNamelessDirectiveAffectsAllRules),
        ("testSingleRule", testSingleRule),
        ("testSpuriousFlags", testSpuriousFlags),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RuleMaskTests.__allTests__RuleMaskTests),
    ]
}
#endif
