//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2019 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

// This file is automatically generated with generate-swift-format. Do not edit!

@_spi(Internal) public enum RuleRegistry {
  public static let rules: [String: Configuration.RuleSeverity] = [
    "AllPublicDeclarationsHaveDocumentation": .disabled,
    "AlwaysUseLiteralForEmptyCollectionInit": .disabled,
    "AlwaysUseLowerCamelCase": .ruleDefault,
    "AmbiguousTrailingClosureOverload": .ruleDefault,
    "AvoidRetroactiveConformances": .ruleDefault,
    "BeginDocumentationCommentWithOneLineSummary": .disabled,
    "DoNotUseSemicolons": .ruleDefault,
    "DontRepeatTypeInStaticProperties": .ruleDefault,
    "FileScopedDeclarationPrivacy": .ruleDefault,
    "FullyIndirectEnum": .ruleDefault,
    "GroupNumericLiterals": .ruleDefault,
    "IdentifiersMustBeASCII": .ruleDefault,
    "NeverForceUnwrap": .disabled,
    "NeverUseForceTry": .disabled,
    "NeverUseImplicitlyUnwrappedOptionals": .disabled,
    "NoAccessLevelOnExtensionDeclaration": .ruleDefault,
    "NoAssignmentInExpressions": .ruleDefault,
    "NoBlockComments": .ruleDefault,
    "NoCasesWithOnlyFallthrough": .ruleDefault,
    "NoEmptyLinesOpeningClosingBraces": .disabled,
    "NoEmptyTrailingClosureParentheses": .ruleDefault,
    "NoLabelsInCasePatterns": .ruleDefault,
    "NoLeadingUnderscores": .disabled,
    "NoParensAroundConditions": .ruleDefault,
    "NoPlaygroundLiterals": .ruleDefault,
    "NoVoidReturnOnFunctionSignature": .ruleDefault,
    "OmitExplicitReturns": .disabled,
    "OneCasePerLine": .ruleDefault,
    "OneVariableDeclarationPerLine": .ruleDefault,
    "OnlyOneTrailingClosureArgument": .ruleDefault,
    "OrderedImports": .ruleDefault,
    "ReplaceForEachWithForLoop": .ruleDefault,
    "ReturnVoidInsteadOfEmptyTuple": .ruleDefault,
    "TypeNamesShouldBeCapitalized": .ruleDefault,
    "UseEarlyExits": .disabled,
    "UseExplicitNilCheckInConditions": .ruleDefault,
    "UseLetInEveryBoundCaseVariable": .ruleDefault,
    "UseShorthandTypeNames": .ruleDefault,
    "UseSingleLinePropertyGetter": .ruleDefault,
    "UseSynthesizedInitializer": .ruleDefault,
    "UseTripleSlashForDocumentationComments": .ruleDefault,
    "UseWhereClausesInForLoops": .disabled,
    "ValidateDocumentationComments": .disabled,
    "AddLines": .ruleDefault,
    "EndOfLineComment": .ruleDefault,
    "Indentation": .ruleDefault,
    "LineLength": .ruleDefault,
    "RemoveLine": .ruleDefault,
    "Spacing": .ruleDefault,
    "SpacingCharacter": .ruleDefault,
    "TrailingComma": .ruleDefault,
    "TrailingWhitespace": .ruleDefault,
  ]
}
