#!/usr/bin/env bash
#
# This script is used to manually generate sources otherwise generated by the
# `generate-pipeline-plugin` build tool, until that tool is working in Windows
# builds. The generated sources will be ignored when building on non-Windows
# platforms.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
PACKAGE_DIR="$(dirname -- "${SCRIPT_DIR}")"
SOURCES_DIR="${PACKAGE_DIR}/Sources"

echo "*** Generating ${SOURCES_DIR}/SwiftFormat/Pipelines+Generated.swift..."

swift run --package-path "${PACKAGE_DIR}" generate-pipeline \
    --sources-directory "${SOURCES_DIR}" \
    --output-file "${SOURCES_DIR}/SwiftFormat/Pipelines+Generated.swift" \
    --target SwiftFormat

echo "*** Generating ${SOURCES_DIR}/SwiftFormatConfiguration/RuleRegistry+Generated.swift..."

swift run --package-path "${PACKAGE_DIR}" generate-pipeline \
    --sources-directory "${SOURCES_DIR}" \
    --output-file "${SOURCES_DIR}/SwiftFormatConfiguration/RuleRegistry+Generated.swift" \
    --target SwiftFormatConfiguration

echo "*** Generating ${SOURCES_DIR}/SwiftFormatRules/RuleNameCache+Generated.swift..."

swift run --package-path "${PACKAGE_DIR}" generate-pipeline \
    --sources-directory "${SOURCES_DIR}" \
    --output-file "${SOURCES_DIR}/SwiftFormatRules/RuleNameCache+Generated.swift" \
    --target SwiftFormatRules

echo "*** Done!"
