#if !canImport(ObjectiveC)
import XCTest

extension WhitespaceLinterPerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WhitespaceLinterPerformanceTests = [
        ("testWhitespaceLinterPerformance", testWhitespaceLinterPerformance),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(WhitespaceLinterPerformanceTests.__allTests__WhitespaceLinterPerformanceTests),
    ]
}
#endif
