name: Publish Release

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      prerelease:
        type: boolean
        description: "Prerelease"
        # Whether to create a prerelease or proper release
        default: true
        required: true
      swift_format_version:
        type: string
        default: 604.0.0
        description: "swift-format version"
        # The version of swift-format to tag. If this is a prerelease, `-prerelease-<date>` is added to this version.
        required: true
      swift_syntax_tag:
        type: string
        default: 604.0.0
        description: "swift-syntax version"
        # The swift-syntax version to depend on. If this is a prerelease, the latest swift-syntax prerelease tag for this version is used.
        required: true

jobs:
  check_triggering_actor:
    name: Check user is allowed to create release
    # Only a single user should be allowed to create releases to avoid two people triggering the creation of a release
    # at the same time. If the release manager changes between users, update this condition.
    runs-on: ubuntu-latest
    steps:
      - env:
          TRIGGERING_ACTOR: ${{ github.triggering_actor }}
        run: |
          if [[ "${TRIGGERING_ACTOR}" != "rintaro" && "${TRIGGERING_ACTOR}" != "hamishknight" ]]; then
            echo "${TRIGGERING_ACTOR} is not allowed to create a release"
            exit 1
          fi
  create_release_commits:
    name: Create release commits
    runs-on: ubuntu-latest
    outputs:
      swift_format_version: ${{ steps.swift_format_version.outputs.swift_format_version }}
      release_commit_patch: ${{ steps.create_release_commits.outputs.release_commit_patch }}
    steps:
      - name: Determine swift-syntax tag to depend on
        id: swift_syntax_tag
        shell: bash
        env:
          INPUT_PRERELEASE: ${{ github.event.inputs.prerelease }}
          INPUT_SWIFT_SYNTAX_TAG: ${{ github.event.inputs.swift_syntax_tag }}
        run: |
          if [[ "${INPUT_PRERELEASE}" == "false" ]]; then
            SWIFT_SYNTAX_TAG="${INPUT_SWIFT_SYNTAX_TAG}"
          else
            git clone https://github.com/swiftlang/swift-syntax.git
            cd swift-syntax
            SWIFT_SYNTAX_TAG="$(git tag | grep "${INPUT_SWIFT_SYNTAX_TAG}"-prerelease | sort -r | head -1)"
          fi

          echo "Using swift-syntax tag: ${SWIFT_SYNTAX_TAG}"
          echo "swift_syntax_tag=${SWIFT_SYNTAX_TAG}" >> "$GITHUB_OUTPUT"
      - name: Determine swift-format prerelease version
        id: swift_format_version
        env:
          INPUT_PRERELEASE: ${{ github.event.inputs.prerelease }}
          INPUT_SWIFT_FORMAT_VERSION: ${{ github.event.inputs.swift_format_version }}
        run: |
          if [[ "${INPUT_PRERELEASE}" == "false" ]]; then
            SWIFT_FORMAT_VERSION="${INPUT_SWIFT_FORMAT_VERSION}"
          else
            SWIFT_FORMAT_VERSION="${INPUT_SWIFT_FORMAT_VERSION}-prerelease-$(date +'%Y-%m-%d')"
          fi
          echo "Using swift-format version: ${SWIFT_FORMAT_VERSION}"
          echo "swift_format_version=${SWIFT_FORMAT_VERSION}" >> "$GITHUB_OUTPUT"
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Create release commits
        id: create_release_commits
        env:
          SWIFT_SYNTAX_TAG: ${{ steps.swift_syntax_tag.outputs.swift_syntax_tag }}
          SWIFT_FORMAT_VERSION: ${{ steps.swift_format_version.outputs.swift_format_version }}
        run: |
          # Without this, we can't perform git operations in GitHub actions.
          git config --global --add safe.directory "$(realpath .)"
          git config --local user.name 'swift-ci'
          git config --local user.email 'swift-ci@users.noreply.github.com'

          BASE_COMMIT=$(git rev-parse HEAD)

          sed -E -i "s#branch: \"(main|release/[0-9]+\.[0-9]+)\"#from: \"${SWIFT_SYNTAX_TAG}\"#" Package.swift
          git add Package.swift
          git commit -m "Change swift-syntax dependency to ${SWIFT_SYNTAX_TAG}"

          sed -E -i "s#print\(\".*\"\)#print\(\"${SWIFT_FORMAT_VERSION}\"\)#" Sources/swift-format/PrintVersion.swift
          git add Sources/swift-format/PrintVersion.swift
          git commit -m "Change version to ${SWIFT_FORMAT_VERSION}"

          {
            echo 'release_commit_patch<<EOF'
            git format-patch "$BASE_COMMIT"..HEAD --stdout
            echo EOF
          } >> "$GITHUB_OUTPUT"
  test:
    name: Test in ${{ matrix.release && 'Release' || 'Debug' }} configuration
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.6
    needs: create_release_commits
    strategy:
      fail-fast: false
      matrix:
        release: [true, false]
    with:
      linux_exclude_swift_versions: "[{\"swift_version\": \"5.9\"}, {\"swift_version\": \"5.10\"}]"
      windows_exclude_swift_versions: "[{\"swift_version\": \"5.9\"}]"
      linux_pre_build_command: |
        git config --global --add safe.directory "$(realpath .)"
        git config --local user.name 'swift-ci'
        git config --local user.email 'swift-ci@users.noreply.github.com'
        git am << EOF
        ${{ needs.create_release_commits.outputs.release_commit_patch }}
        EOF
      windows_pre_build_command: |
        git config --local user.name "swift-ci"
        git config --local user.email "swift-ci@users.noreply.github.com"
        echo @"
        ${{ needs.create_release_commits.outputs.release_commit_patch }}
        "@ > $env:TEMP\patch.diff
        # For some reason `git am` fails in Powershell with the following error. Executing it in cmd works...
        # fatal: empty ident name (for <>) not allowed
        cmd /c "type $env:TEMP\patch.diff | git am || (exit /b 1)"
      # We require that releases of swift-format build without warnings
      linux_build_command: swift test -Xswiftc -warnings-as-errors ${{ matrix.release && '-c release' || '' }}
      windows_build_command: Invoke-Program swift test -Xswiftc -warnings-as-errors ${{ matrix.release && '-c release' || '' }}
  create_tag:
    name: Create Tag
    runs-on: ubuntu-latest
    needs: [check_triggering_actor, test, create_release_commits]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Apply release commits
        env:
          RELEASE_COMMIT_PATCH: ${{ needs.create_release_commits.outputs.release_commit_patch }}
        run: |
          git config --global --add safe.directory "$(realpath .)"
          git config --local user.name 'swift-ci'
          git config --local user.email 'swift-ci@users.noreply.github.com'
          echo "${RELEASE_COMMIT_PATCH}" | git am
      - name: Tag release
        env:
          SWIFT_FORMAT_VERSION: ${{ needs.create_release_commits.outputs.swift_format_version }}
        run: |
          git tag "${SWIFT_FORMAT_VERSION}"
          git push origin "${SWIFT_FORMAT_VERSION}"
  create_prerelease:
    name: Create prerelease on GitHub
    runs-on: ubuntu-latest
    needs: [create_release_commits, create_tag]
    # Only create a release automatically for prereleases. For real releases, release notes should be crafted by hand.
    if: ${{ github.event.inputs.prerelease }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          SWIFT_FORMAT_VERSION: ${{ needs.create_release_commits.outputs.swift_format_version }}
        run: |
          gh release create "${SWIFT_FORMAT_VERSION}" \
            --title "${SWIFT_FORMAT_VERSION}" \
            --prerelease
